from __future__ import annotations

from pathlib import Path
import shutil

from .analysis import build_daily_summary, build_weekly_summary
from .catalog_page import CATALOG_SCRIPT, catalog_body
from .catalog_history import build_catalog_history
from .storage import write_json


STYLE = """
:root{color-scheme:light;--paper:oklch(98.2% .006 105);--surface:oklch(100% 0 0);--surface-tint:oklch(96.7% .012 112);--ink:oklch(25% .025 120);--muted:oklch(48% .022 120);--line:oklch(87% .018 112);--line-strong:oklch(73% .026 112);--accent:oklch(43% .075 145);--accent-soft:oklch(94% .025 145);--warning:oklch(48% .09 63);--warning-soft:oklch(95% .03 75);--focus:oklch(60% .15 245);--radius:8px;--shadow:0 12px 34px oklch(25% .02 120/.08)}
*{box-sizing:border-box}[hidden]{display:none!important}html{scroll-behavior:smooth}body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.5 ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}button,input,select{font:inherit;color:inherit}button,select{cursor:pointer}a{color:var(--accent);text-underline-offset:3px}a:hover{text-decoration-thickness:2px}a:focus-visible,button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid var(--focus);outline-offset:2px}
.site-header{border-bottom:1px solid var(--line);background:color-mix(in oklch,var(--paper) 94%,white);position:sticky;top:0;z-index:20}.site-header-inner{max-width:1440px;margin:auto;min-height:62px;padding:.65rem 1.5rem;display:flex;align-items:center;justify-content:space-between;gap:2rem}.site-identity{display:flex;align-items:baseline;gap:.55rem;text-decoration:none;color:var(--ink);white-space:nowrap}.site-identity strong{font-size:1rem}.site-identity span{color:var(--muted);font-size:.8rem}.site-nav{display:flex;gap:.25rem;flex-wrap:wrap}.site-nav a{padding:.45rem .65rem;border-radius:6px;color:var(--muted);text-decoration:none}.site-nav a:hover{background:var(--surface-tint);color:var(--ink)}.site-nav a[aria-current="page"]{background:var(--accent-soft);color:var(--accent);font-weight:650}
main{max-width:1120px;margin:auto;padding:2rem 1.5rem 4rem}.catalog-page main{max-width:1500px;padding-top:1.5rem}.site-footer{border-top:1px solid var(--line);color:var(--muted)}.site-footer p{max-width:1120px;margin:auto;padding:1.5rem}.hero{padding:2rem 0}.hero h1,.catalog-heading h1{margin:.15rem 0;font-size:clamp(2rem,5vw,3.25rem);line-height:1.05;letter-spacing:-.035em}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:1rem}.card{background:var(--surface);border:1px solid var(--line);border-radius:var(--radius);padding:1rem}.metric{font-size:1.8rem;font-weight:720;font-variant-numeric:tabular-nums}.muted,.quiet{color:var(--muted)}.healthy{color:var(--accent);font-weight:700}.gap{color:var(--warning)}table{width:100%;border-collapse:collapse;background:var(--surface)}th,td{text-align:left;padding:.65rem;border-bottom:1px solid var(--line);vertical-align:top}th{font-size:.74rem;letter-spacing:.04em;text-transform:uppercase;color:var(--muted)}
.catalog-heading{display:flex;align-items:end;justify-content:space-between;gap:2rem;padding:1rem 0 1.5rem}.eyebrow{margin:0;color:var(--accent);font-size:.75rem;font-weight:750;letter-spacing:.09em;text-transform:uppercase}.lede{max-width:660px;margin:.65rem 0 0;color:var(--muted);font-size:1rem}.catalog-scope{display:grid;grid-template-columns:repeat(3,minmax(105px,1fr));min-width:min(520px,48vw);margin:0;border-top:1px solid var(--line-strong);border-bottom:1px solid var(--line)}.catalog-scope div{padding:.85rem}.catalog-scope div+div{border-left:1px solid var(--line)}.catalog-scope dt{color:var(--muted);font-size:.72rem;text-transform:uppercase;letter-spacing:.05em}.catalog-scope dd{margin:.2rem 0 0;font-size:1.15rem;font-weight:680;font-variant-numeric:tabular-nums}
.catalog-controls{background:var(--surface-tint);border:1px solid var(--line);border-radius:var(--radius);padding:1rem 1.1rem}.controls-heading,.results-toolbar{display:flex;align-items:center;justify-content:space-between;gap:1rem}.controls-heading h2{margin:0;font-size:1rem}.controls-heading p{margin:.15rem 0 0;color:var(--muted);font-size:.82rem}.filter-grid{display:grid;grid-template-columns:minmax(250px,1.7fr) repeat(3,minmax(140px,1fr));gap:.8rem;margin-top:.9rem}.filter-grid>label,.toolbar-actions label{display:flex;flex-direction:column;gap:.3rem;color:var(--muted);font-size:.75rem;font-weight:650}.filter-grid input,.filter-grid select,.toolbar-actions select{width:100%;min-height:40px;border:1px solid var(--line-strong);border-radius:6px;background:var(--surface);padding:.48rem .6rem}.search-field{grid-column:span 2}.price-filter,.check-filters{border:0;padding:0;margin:0;grid-column:span 2}.filter-legend,.check-filters legend{display:block;margin-bottom:.3rem;color:var(--muted);font-size:.75rem;font-weight:650}.price-fields{display:flex;gap:.75rem}.price-filter label{display:flex;flex:1;flex-direction:column;gap:.3rem;color:var(--muted);font-size:.72rem}.check-filters{display:flex;gap:.75rem;align-items:center;flex-wrap:wrap}.check-filters legend{width:100%}.check-filters label{display:flex;align-items:center;gap:.45rem;background:var(--surface);border:1px solid var(--line);border-radius:6px;padding:.55rem .65rem;font-size:.78rem}.check-filters input{width:1rem;min-height:auto;margin:0}.text-button{border:0;background:transparent;color:var(--accent);padding:.4rem}.secondary-button{border:1px solid var(--line-strong);border-radius:6px;background:var(--surface);padding:.48rem .7rem}.secondary-button:hover{border-color:var(--accent);color:var(--accent)}.secondary-button:disabled{cursor:not-allowed;opacity:.45}.catalog-status{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}
.catalog-workspace{display:grid;grid-template-columns:minmax(0,1fr) minmax(340px,410px);gap:1rem;align-items:start;margin-top:1rem}.results-pane,.detail-panel{background:var(--surface);border:1px solid var(--line);border-radius:var(--radius)}.results-toolbar{padding:.8rem 1rem;border-bottom:1px solid var(--line)}.results-toolbar p{margin:0;font-variant-numeric:tabular-nums;font-weight:650}.toolbar-actions{display:flex;align-items:end;gap:.55rem}.toolbar-actions label{min-width:112px}.table-scroll{overflow:auto}.catalog-table{table-layout:fixed}.catalog-table th:nth-child(1){width:42%}.catalog-table th:nth-child(2){width:18%}.catalog-table th:nth-child(3){width:18%}.catalog-table th:nth-child(4){width:22%}.catalog-table td{height:74px}.catalog-table tr.selected td{background:var(--accent-soft)}.catalog-table tr.selected td:first-child{box-shadow:inset 3px 0 var(--accent)}.item-button{display:flex;flex-direction:column;gap:.15rem;width:100%;padding:0;border:0;background:transparent;text-align:left;color:var(--ink)}.item-button strong{font-size:.9rem}.item-button span,.date-note{display:block;color:var(--muted);font-size:.72rem}.price-value{font-weight:700;font-variant-numeric:tabular-nums}.tags{display:flex;gap:.3rem;flex-wrap:wrap}.tag{display:inline-block;border:1px solid var(--line-strong);border-radius:999px;padding:.15rem .42rem;font-size:.68rem;white-space:nowrap}.tag.promoted{border-color:color-mix(in oklch,var(--accent),white 55%);background:var(--accent-soft);color:var(--accent)}.tag.missing{border-color:color-mix(in oklch,var(--warning),white 55%);background:var(--warning-soft);color:var(--warning)}.pagination{display:flex;align-items:center;justify-content:center;gap:.8rem;padding:.8rem;border-top:1px solid var(--line)}.pagination span{min-width:110px;text-align:center;color:var(--muted);font-size:.8rem}.empty-state,.detail-placeholder,.error-state{display:flex;flex-direction:column;gap:.35rem;align-items:center;justify-content:center;text-align:center;padding:3rem;color:var(--muted)}
.detail-panel{position:sticky;top:78px;max-height:calc(100vh - 94px);overflow:auto;box-shadow:var(--shadow)}.detail-close{display:none}.detail-content{padding:1rem}.detail-header{display:grid;grid-template-columns:92px 1fr;gap:1rem;align-items:start}.detail-header img,.image-placeholder{width:92px;height:92px;object-fit:contain;border:1px solid var(--line);border-radius:6px;background:white}.image-placeholder{display:grid;place-items:center;color:var(--muted);font-size:.72rem}.detail-header h2{margin:.22rem 0;font-size:1.25rem;line-height:1.25}.detail-price{margin:.3rem 0 0;font-size:1.45rem;font-weight:760;font-variant-numeric:tabular-nums}.detail-state{margin:.2rem 0;color:var(--muted);font-size:.76rem}.detail-actions{display:flex;align-items:center;gap:.8rem;margin:1rem 0;padding-bottom:1rem;border-bottom:1px solid var(--line);font-size:.78rem}.evidence-list{margin:0}.evidence-list div{display:grid;grid-template-columns:135px 1fr;gap:.75rem;padding:.48rem 0;border-bottom:1px solid var(--line)}.evidence-list dt{color:var(--muted);font-size:.74rem}.evidence-list dd{margin:0;font-size:.78rem;overflow-wrap:anywhere}.evidence-list code{font-size:.7rem}.category-evidence,.history-evidence{margin-top:1.2rem}.category-evidence h3,.history-evidence h3{margin:0 0 .45rem;font-size:.9rem}.category-evidence ul{margin:0;padding-left:1.1rem;color:var(--muted);font-size:.76rem}.history-evidence>div>p{margin:0 0 .7rem;color:var(--muted);font-size:.75rem}.history-scroll{max-height:340px;overflow:auto;border:1px solid var(--line);border-radius:6px}.history-scroll table{font-size:.72rem}.history-scroll th{position:sticky;top:0;background:var(--surface-tint);z-index:1}.history-scroll td:nth-child(1){white-space:nowrap}.history-scroll td:nth-child(2){font-variant-numeric:tabular-nums;white-space:nowrap}.history-scroll td span{display:block}.history-scroll small{color:var(--muted)}.history-gap td{background:var(--warning-soft)}.gap-label{color:var(--warning);font-weight:700}.catalog-contract{margin:1rem 0 0;text-align:right;font-size:.8rem}
@media(max-width:1050px){.filter-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.search-field{grid-column:span 2}.catalog-workspace{grid-template-columns:minmax(0,1fr) 350px}.toolbar-actions{flex-wrap:wrap;justify-content:end}.catalog-table th:nth-child(2),.catalog-table td:nth-child(2){display:none}.catalog-table th:nth-child(1){width:45%}.catalog-table th:nth-child(3){width:25%}.catalog-table th:nth-child(4){width:30%}}
@media(max-width:760px){.site-header{position:static}.site-header-inner{align-items:flex-start;flex-direction:column;gap:.45rem;padding:.75rem 1rem}.site-nav{width:100%;overflow:auto;flex-wrap:nowrap}.site-nav a{white-space:nowrap}.catalog-page main,main{padding:1.1rem 1rem 3rem}.catalog-heading{align-items:start;flex-direction:column;gap:1rem}.catalog-scope{width:100%;min-width:0}.catalog-scope dd{font-size:.95rem}.filter-grid{grid-template-columns:1fr}.search-field,.price-filter,.check-filters{grid-column:span 1}.price-fields{flex-wrap:wrap}.results-toolbar{align-items:flex-start;flex-direction:column}.toolbar-actions{width:100%;justify-content:flex-start}.toolbar-actions label{flex:1}.catalog-table th:nth-child(4),.catalog-table td:nth-child(4){display:none}.catalog-table th:nth-child(1){width:62%}.catalog-table th:nth-child(3){width:38%}.catalog-workspace{display:block}.detail-panel{display:none;position:fixed;z-index:50;inset:1rem 0 0 1.5rem;max-height:none;border-radius:10px 0 0 0;box-shadow:-20px 0 60px oklch(20% .03 120/.22)}.detail-panel.is-open{display:block}.detail-close{display:block;position:sticky;top:0;z-index:2;width:100%;border:0;border-bottom:1px solid var(--line);background:var(--surface-tint);padding:.7rem;text-align:right;color:var(--accent)}.site-footer p{padding:1rem}.catalog-contract{text-align:left}}
@media(max-width:480px){.catalog-scope{grid-template-columns:1fr}.catalog-scope div+div{border-left:0;border-top:1px solid var(--line)}.toolbar-actions{display:grid;grid-template-columns:1fr 1fr}.toolbar-actions .secondary-button{grid-column:span 2}.catalog-table th:nth-child(3),.catalog-table td:nth-child(3){display:none}.catalog-table th:nth-child(1){width:100%}.detail-header{grid-template-columns:72px 1fr}.detail-header img,.image-placeholder{width:72px;height:72px}.evidence-list div{grid-template-columns:115px 1fr}}
"""

NAV_ITEMS = (("Overview", "index.html", "overview"), ("Daily", "daily-report.html", "daily"), ("Weekly", "weekly-report.html", "weekly"), ("Catalog", "catalog.html", "catalog"), ("Methodology", "METHODOLOGY.html", "methodology"))


def _page(title: str, body: str, script: str = "", *, current: str = "", body_class: str = "") -> str:
    links = "".join(
        f'<a href="{href}"{(" aria-current=\"page\"" if key == current else "")}>{label}</a>'
        for label, href, key in NAV_ITEMS
    )
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f7f8f2"><title>{title}</title><link rel="stylesheet" href="assets/site.css?v=catalog-1.2"></head><body class="{body_class}"><header class="site-header"><div class="site-header-inner"><a class="site-identity" href="index.html"><strong>Gala Fresh Baldwin</strong><span>catalog research</span></a><nav class="site-nav" aria-label="Research reports">{links}</nav></div></header><main>{body}</main><footer class="site-footer"><p>Independent, unaffiliated research. Source: <a href="https://www.shopgalafresh.com/">Gala Fresh public storefront</a>. Online values are not asserted as physical shelf prices.</p></footer>{script}</body></html>"""


def _summary_script(source: str, weekly: bool = False) -> str:
    keys = "['latest_catalog_size','median_catalog_size','median_valid_price_percentage','price_increases','price_decreases','additions','returns','missing_products']" if weekly else "['catalog_size','valid_price_percentage','median_regular_price','products_with_promotions']"
    target = "data" if weekly else "data.latest"
    return f"""<script>fetch('{source}').then(r=>r.json()).then(data=>{{const source={target};const labels={{catalog_size:'Catalog products',valid_price_percentage:'Valid prices %',median_regular_price:'Median regular price',products_with_promotions:'Products promoted',latest_catalog_size:'Latest catalog',median_catalog_size:'Median catalog',median_valid_price_percentage:'Median valid prices %',price_increases:'Price increases',price_decreases:'Price decreases',additions:'Additions',returns:'Returns',missing_products:'Missing observations'}};document.querySelector('#status').textContent=data.status;document.querySelector('#metrics').innerHTML={keys}.map(k=>`<section class="card"><div class="metric">${{source[k]??'—'}}</div><div>${{labels[k]}}</div></section>`).join('');document.querySelector('#raw').href='{source}';}}).catch(e=>document.querySelector('#status').textContent='Report data unavailable');</script>"""


def _daily_script() -> str:
    return """<script>const esc=s=>String(s??'—').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));const priceRows=rows=>rows.slice(0,25).map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.previous_regular_price)}</td><td>${esc(x.current_regular_price)}</td><td>${esc(x.change_percentage)}%</td></tr>`).join('')||'<tr><td colspan="4">None reported</td></tr>';fetch('data/daily-summary.json').then(r=>r.json()).then(d=>{status.textContent=d.status;const x=d.latest;metrics.innerHTML=[['Catalog products',x.catalog_size],['Valid prices %',x.valid_price_percentage],['Promoted products',x.products_with_promotions],['Prior overlap %',d.comparison?.prior_overlap_percentage??'—']].map(([k,v])=>`<section class="card"><div class="metric">${esc(v)}</div><div>${k}</div></section>`).join('');increases.innerHTML=priceRows(d.price_increases);decreases.innerHTML=priceRows(d.price_decreases);assortment.textContent=d.comparison?`${d.comparison.additions} additions; ${d.comparison.returns} returns; ${d.comparison.missing_products} missing observations`:'Comparisons begin with the second healthy snapshot.';promotions.textContent=`${d.promotion_changes.active} active; ${d.promotion_changes.start_count} starts; ${d.promotion_changes.end_count} ends; ${d.promotion_changes.change_count} changes`;anomalies.textContent=`${d.anomalies.length} conservative flags`;}).catch(()=>status.textContent='Report data unavailable')</script>"""


def _weekly_script() -> str:
    return """<script>const esc=s=>String(s??'—').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));fetch('data/weekly-summary.json').then(r=>r.json()).then(d=>{status.textContent=d.status;metrics.innerHTML=[['Latest catalog',d.latest_catalog_size],['Median catalog',d.median_catalog_size],['Median valid prices %',d.median_valid_price_percentage],['Snapshot days',d.snapshot_days]].map(([k,v])=>`<section class="card"><div class="metric">${esc(v)}</div><div>${k}</div></section>`).join('');totals.textContent=`${d.price_increases} price increases; ${d.price_decreases} decreases; ${d.additions} additions; ${d.returns} returns; ${d.missing_products} missing observations`;history.innerHTML=d.daily_history.map(x=>`<tr><td>${esc(x.snapshot_date)}</td><td>${esc(x.catalog_size)}</td><td>${esc(x.valid_price_percentage)}%</td><td>${esc(x.products_with_promotions)}</td></tr>`).join('')||'<tr><td colspan="4">Awaiting baseline</td></tr>';}).catch(()=>status.textContent='Report data unavailable')</script>"""


def build_reports(snapshot_dir: Path, docs_dir: Path) -> tuple[dict, dict]:
    data_dir = docs_dir / "data"
    assets = docs_dir / "assets"
    assets.mkdir(parents=True, exist_ok=True)
    daily = build_daily_summary(snapshot_dir)
    weekly = build_weekly_summary(daily)
    write_json(data_dir / "daily-summary.json", daily)
    write_json(data_dir / "weekly-summary.json", weekly)
    history_dir = data_dir / "catalog-history"
    if history_dir.exists():
        shutil.rmtree(history_dir)
    catalog_index = build_catalog_history(snapshot_dir, history_dir)
    (assets / "site.css").write_text(STYLE.strip() + "\n", encoding="utf-8")
    (assets / "catalog.js").write_text(CATALOG_SCRIPT.strip() + "\n", encoding="utf-8")
    overview = '<section class="hero"><h1>Gala Fresh Baldwin catalog research</h1><p>Daily, transparent history of the anonymously visible public online catalog.</p><p>Pipeline: <span id="status" class="healthy">Loading…</span></p></section><section id="metrics" class="grid" aria-live="polite"></section><p><a id="raw" href="data/daily-summary.json">Machine-readable daily contract</a></p>'
    (docs_dir / "index.html").write_text(_page("Gala Fresh Baldwin Research", overview, _summary_script("data/daily-summary.json"), current="overview"), encoding="utf-8")
    daily_body = '<h1>Daily report</h1><p>Latest daily changes, with missing observations preserved as gaps.</p><p>Status: <span id="status">Loading…</span></p><section id="metrics" class="grid"></section><h2>Assortment</h2><p id="assortment"></p><h2>Promotions</h2><p id="promotions"></p><h2>Anomalies</h2><p id="anomalies"></p><h2>Regular-price increases</h2><table><thead><tr><th>Product</th><th>Previous</th><th>Current</th><th>Change</th></tr></thead><tbody id="increases"></tbody></table><h2>Regular-price decreases</h2><table><thead><tr><th>Product</th><th>Previous</th><th>Current</th><th>Change</th></tr></thead><tbody id="decreases"></tbody></table><p><a href="data/daily-summary.json">Daily JSON contract</a></p>'
    (docs_dir / "daily-report.html").write_text(_page("Daily report", daily_body, _daily_script(), current="daily"), encoding="utf-8")
    weekly_body = '<h1>Weekly report</h1><p>A less noisy seven-snapshot research readout.</p><p>Status: <span id="status">Loading…</span></p><section id="metrics" class="grid"></section><p id="totals"></p><table><thead><tr><th>Date</th><th>Catalog</th><th>Valid prices</th><th>Promoted products</th></tr></thead><tbody id="history"></tbody></table><p><a href="data/weekly-summary.json">Weekly JSON contract</a></p>'
    (docs_dir / "weekly-report.html").write_text(_page("Weekly report", weekly_body, _weekly_script(), current="weekly"), encoding="utf-8")
    catalog_html = _page(
        "Catalog | Gala Fresh Baldwin Research",
        catalog_body(catalog_index),
        '<script src="assets/catalog.js?v=catalog-1.2" defer></script>',
        current="catalog",
        body_class="catalog-page",
    )
    (docs_dir / "catalog.html").write_text(catalog_html, encoding="utf-8")
    legacy_redirect = """<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="0; url=catalog.html"><link rel="canonical" href="catalog.html"><title>Catalog</title></head><body><p>This page has moved to <a href="catalog.html">Catalog</a>.</p></body></html>"""
    (docs_dir / "catalog-history.html").write_text(legacy_redirect, encoding="utf-8")
    methodology_md = docs_dir / "METHODOLOGY.md"
    if methodology_md.exists():
        paragraphs = methodology_md.read_text(encoding="utf-8").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        html = "<h1>Methodology</h1><pre style=\"white-space:pre-wrap;font:inherit\">" + paragraphs + "</pre>"
        (docs_dir / "METHODOLOGY.html").write_text(_page("Methodology", html, current="methodology"), encoding="utf-8")
    (docs_dir / ".nojekyll").write_text("", encoding="utf-8")
    return daily, weekly
